version: "3.1"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
