name: Run Tests

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Psycopg3 binaries
        run: pip install "psycopg[binary,pool]"
      - name: Install dependencies
        run: pip install -e .
      - name: Install dev dependencies
        run: pip install -e '.[dev]'
      - name: Check Ruff Linter
        run: ruff check src
      - name: Run docker compose
        run: docker compose -f docker-compose.test.yml up -d
      - name: Create .env file
        run: |
          touch .env
          echo "DATABASE_URL=postgresql+psycopg://postgres:mysecretpassword@localhost:5432/postgres" >> .env
      - name: Run tests
        run: coverage run -m unittest discover src
      - name: Generate coverage report
        run: coverage xml
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
